import { Opportunity, ApplicationTrackerCard, ActivityLog } from './types';

export const mockOpportunities: Opportunity[] = [
  {
    id: 'gsoc-2025',
    title: 'Google Summer of Code 2025',
    organization: 'Google Open Source',
    logo: '☁',
    category: 'Open Source',
    description: 'Contribute to open-source organizations while earning a generous stipend and receiving expert mentorship from senior maintainers worldwide.',
    longDescription: 'Google Summer of Code is a global program focused on bringing more student and beginner developers into open source software development. Selected developers are paired with a mentor from an open source organization, gaining exposure to real-world software development scenarios and learning technologies like React, Rust, Go, Python, and Linux kernel modules. Students work on a 12-week programming project with their host organization.',
    stipend: '$3,000 stipends',
    location: 'Remote, Global',
    deadlineDate: '2026-06-09',
    daysLeft: 5,
    skillsRequired: ['Git', 'Python', 'Go', 'Rust', 'Open Source', 'Docker'],
    difficulty: 'Intermediate',
    matchScore: 94,
    isFeatured: true
  },
  {
    id: 'mlh-hackathon-2025',
    title: 'MLH Global Catalyst Hackathon',
    organization: 'Major League Hacking',
    logo: '🏆',
    category: 'Hackathons',
    description: 'Build innovative hardware or software projects in 48 hours and compete with developers from 200+ countries for amazing awards and sponsor pipelines.',
    longDescription: 'Join thousands of students and builders for the MLH Global Catalyst Hackathon. This 48-hour virtual hackathon offers challenges across Web3, Artificial Intelligence, Mobile development, and Cloud Computing. Work in teams of up to 4, participate in workshops hosted by top tech companies, and win prizes from a total pool exceeding $15,000.',
    stipend: '$15k+ Prizes / Travel Grants',
    location: 'Virtual / San Francisco, CA',
    deadlineDate: '2026-06-07',
    daysLeft: 3,
    skillsRequired: ['React.js', 'Node.js', 'FastAPI', 'UI Design', 'Pitching', 'Tailwind CSS'],
    difficulty: 'Beginner',
    matchScore: 89,
    isFeatured: true
  },
  {
    id: 'fulbright-scholarship',
    title: 'Fulbright Graduate Fellowship Program',
    organization: 'US Department of State',
    logo: '🎓',
    category: 'Scholarships',
    description: 'Full-funding fellowships for postgraduate studies, covering luxury tuition, health insurance, airfare, and monthly academic living stipends.',
    longDescription: 'The Fulbright program is one of the most prestigious international education exchange programs in the world. It provides full scholarships for students to pursue Master or PhD degrees at elite universities in the United States. Recipients are selected based on academic excellence, leadership potential, and commitment to cross-cultural understanding.',
    stipend: 'Full Funding + Monthly Allowance',
    location: 'United States',
    deadlineDate: '2026-06-12',
    daysLeft: 8,
    skillsRequired: ['Research', 'Leadership', 'Academic Writing', 'Public Speaking'],
    difficulty: 'Advanced',
    matchScore: 78,
    isFeatured: true
  },
  {
    id: 'meta-swe-intern',
    title: 'Meta Software Engineering Internship',
    organization: 'Meta Platforms Inc.',
    logo: '💼',
    category: 'Internships',
    description: 'Work alongside world-class engineers on products like Instagram, Quest, and Meta AI with competitive salaries and high return-offer rates.',
    longDescription: 'Meta is looking for Software Engineering Interns to join our teams. In this role, you will write production-grade code, participate in code reviews, ship features to billions of users, and learn from top developers. You will be paired with a 1-to-1 mentor and enjoy extensive intern networking events, hackathons, and housing stipends.',
    stipend: '$8,500/mo + Housing',
    location: 'Menlo Park, CA (Hybrid)',
    deadlineDate: '2026-06-15',
    daysLeft: 11,
    skillsRequired: ['C++', 'Python', 'Systems', 'Algorithms', 'React', 'GraphQL'],
    difficulty: 'Advanced',
    matchScore: 92,
    isFeatured: true
  },
  {
    id: 'girlscript-soc',
    title: 'GirlScript Summer of Code 2025',
    organization: 'GirlScript Foundation',
    logo: '🌸',
    category: 'Open Source',
    description: 'Three-month-long open source program designed to help beginners start their journey in open source software development under expert guides.',
    longDescription: 'GirlScript Summer of Code is the largest open-source development program in India. It aims to prepare student developers for major global open source programs like GSoC. Participants contribute to real projects under the guidance of experienced mentors, earn badges, work on Github/Gitlab, and compete for top contributor rewards.',
    stipend: 'Certificates & Merch',
    location: 'Remote, India',
    deadlineDate: '2026-06-16',
    daysLeft: 12,
    skillsRequired: ['Git', 'HTML/CSS', 'JavaScript', 'Node.js', 'UI Design'],
    difficulty: 'Beginner',
    matchScore: 96,
    isFeatured: true
  },
  {
    id: 'yc-fellowship',
    title: 'YC Startup Founder Fellowship 2025',
    organization: 'Y Combinator',
    logo: '🚀',
    category: 'Fellowships',
    description: 'Funding, mentorship, and extensive workspace resources from Y Combinator to help early-stage student founders start companies and raise seed rounds.',
    longDescription: 'The Y Combinator Fellowship is designed for students and builders working on innovative early-stage startups. Get access to the world-renowned YC startup school, peer mentorship, office hours with YC partners, and pre-seed investment opportunities to launch your startup full-time.',
    stipend: '$100K Seed Funding Opportunity',
    location: 'Remote / Silicon Valley',
    deadlineDate: '2026-06-25',
    daysLeft: 21,
    skillsRequired: ['Entrepreneurship', 'Pitching', 'MVP Development', 'Growth Hacking'],
    difficulty: 'Advanced',
    matchScore: 81,
    isFeatured: true
  },
  {
    id: 'mit-undergrad-research',
    title: 'MIT Summer Research Program (MSRP)',
    organization: 'Massachusetts Institute of Technology',
    logo: '🔬',
    category: 'Fellowships',
    description: 'Work inside top-tier MIT labs alongside world-leading professors in Artificial Intelligence, Biology, Materials Science, and Robotics.',
    longDescription: 'MSRP seeks to identify talented undergraduates who could benefit from spending a summer working in a laboratory at MIT. The program is designed to encourage students to pursue academic and research careers, providing full research training, graduate school prep workshops, and competitive weekly stipends.',
    stipend: '$6,000 Stipend + Travel + Housing',
    location: 'Cambridge, MA',
    deadlineDate: '2026-06-30',
    daysLeft: 26,
    skillsRequired: ['Research', 'Mathematics', 'Machine Learning', 'Data Analysis', 'Python'],
    difficulty: 'Advanced',
    matchScore: 85,
    isFeatured: false
  },
  {
    id: 'stripe-remote-backend',
    title: 'Stripe API Backend Intern (Remote)',
    organization: 'Stripe, Inc.',
    logo: '💳',
    category: 'Remote Jobs',
    description: 'Design, optimize, and maintain payment APIs processed by millions of vendors globally in a highly collaborative remote team environment.',
    longDescription: 'Stripe is looking for a remote backend software engineering intern to join our Core Architecture group. You will help build reliable payment infrastructure, design clean APIs in Ruby/Go, and solve distributed systems challenges with top engineers across all time zones.',
    stipend: '$7,800/mo + Home Office Grant',
    location: 'Remote, US / Canada',
    deadlineDate: '2026-06-22',
    daysLeft: 18,
    skillsRequired: ['Ruby', 'Go', 'REST APIs', 'SQL', 'Distributed Systems'],
    difficulty: 'Intermediate',
    matchScore: 88,
    isFeatured: false
  },
  {
    id: 'revel-startup-intern',
    title: 'Early Stage AI Product Intern',
    organization: 'Revel Systems / Stealth Startup',
    logo: '🦄',
    category: 'Startups',
    description: 'Work directly with the co-founders of a high-growth VC-backed Generative AI startup to construct React clients and integrate Google Gemini models.',
    longDescription: 'Join a fast-paced team of 5 engineers building the future of automated code review. As a Product Intern, you will deploy React/Vite frontends, test Node backends, and experiment with Generative LLM agent architectures under direct VC seed funding.',
    stipend: '$4,000/mo + Equity options',
    location: 'San Francisco, CA / Hybrid',
    deadlineDate: '2026-06-14',
    daysLeft: 10,
    skillsRequired: ['React.js', 'TypeScript', 'Tailwind CSS', 'Node.js', 'LLMs', 'Git'],
    difficulty: 'Intermediate',
    matchScore: 90,
    isFeatured: false
  },
  {
    id: 'microsoft-learn-ambassador',
    title: 'Microsoft Learn Student Ambassador',
    organization: 'Microsoft Corp.',
    logo: '💻',
    category: 'Workshops',
    description: 'Build your local developer community, learn cloud tech with free Azure credits, and run tech workshops supported directly by Microsoft.',
    longDescription: 'Become a student leader in your university. Build communities, deliver tech workshops on AI, Cloud, or Dev Tools, and unlock exclusive Azure credits, Visual Studio Enterprise subscriptions, discount vouchers for professional exams, and internship pipelines at Microsoft.',
    stipend: 'Free Credits, Certifications & Swag',
    location: 'Global (Local University)',
    deadlineDate: '2026-07-15',
    daysLeft: 41,
    skillsRequired: ['Public Speaking', 'Community Building', 'Azure', 'Technical Writing'],
    difficulty: 'Beginner',
    matchScore: 93,
    isFeatured: false
  },
  {
    id: 'next-gen-ux-comp',
    title: 'NextGen Interface Design Contest',
    organization: 'Figma Community Network',
    logo: '🥇',
    category: 'Competitions',
    description: 'Showcase your creative product interface talent. Design a futuristic spatial augmented-reality workspace platform in Figma and win top hardware prizes.',
    longDescription: 'This year\'s NextGen Interface Design Contest invites global student UX designers to envision how we will interact with spatial computing platforms in 2030. Submit interactive high-fidelity Figma prototypes and gain constructive critique from lead UX designers of Apple, Figma, and Netflix.',
    stipend: '$5,000 Cash + Wacom Tablets',
    location: 'Virtual',
    deadlineDate: '2026-06-20',
    daysLeft: 16,
    skillsRequired: ['Figma', 'UI Design', 'UX Research', 'Case Study'],
    difficulty: 'Beginner',
    matchScore: 82,
    isFeatured: false
  },
  {
    id: 'tech-climate-con',
    title: 'Tech & Climate Global Conference',
    organization: 'UNESCO Climate Taskforce',
    logo: '🌍',
    category: 'Conferences',
    description: 'Fully funded student travel passes to attend the premier event on software models combating climate change, in Oslo, Norway.',
    longDescription: 'UNESCO is sponsoring 100 fully-funded student delegates to travel to Oslo, Norway, for the annual Tech & Climate Summit. Meet industry executives, listen to keynotes on carbon modeling via AI, participate in standardizing panels, and present your tech solution paper on sustainability.',
    stipend: 'Full Travel, Hotel, and Ticket Cover',
    location: 'Oslo, Norway',
    deadlineDate: '2026-06-28',
    daysLeft: 24,
    skillsRequired: ['Sustainability', 'Technical Writing', 'Data Science', 'Presentation'],
    difficulty: 'Intermediate',
    matchScore: 76,
    isFeatured: false
  },
  {
    id: 'rust-kernels-workshop',
    title: 'Writing Safe Systems with Rust',
    organization: 'Mozilla Learning Labs',
    logo: '🎯',
    category: 'Workshops',
    description: 'A 5-day hands-on intensive workshop designed to master memory safety, async runtimes, and building enterprise APIs in Rust.',
    longDescription: 'Join Mozilla engineers for this technical fast-track series: build fully functional CLI web-scrapers, practice thread pooling, and design ultra-performant memory-safe web servers. All participants receive verified certificates and access to a private Rust Dev job referral pipeline.',
    stipend: 'Verified Certificate & Job Referrals',
    location: 'Virtual',
    deadlineDate: '2026-06-18',
    daysLeft: 14,
    skillsRequired: ['Rust', 'Systems Programming', 'Git', 'Linux'],
    difficulty: 'Intermediate',
    matchScore: 87,
    isFeatured: false
  },
  {
    id: 'hal-bio-fellowship',
    title: 'HAL Computational Genomics Fellowship',
    organization: 'HAL Institute of BioTech',
    logo: '🧬',
    category: 'Fellowships',
    description: 'Join elite researchers analyzing cancer sequences using computational models and neural networks.',
    longDescription: 'Computational genomes are remodeling healthcare. The HAL fellows spend 6 months using PyTorch and bioinformatics algorithms to identify cell mutations. Requires Python and high mathematical acumen.',
    stipend: '$5,000 allowance + Travel',
    location: 'Boston, MA (Hybrid)',
    deadlineDate: '2026-07-10',
    daysLeft: 36,
    skillsRequired: ['Python', 'PyTorch', 'Data Analysis', 'Mathematics', 'Biology'],
    difficulty: 'Advanced',
    matchScore: 71,
    isFeatured: false
  },
  {
    id: 'airbnb-fullstack-intern',
    title: 'Airbnb Fullstack Intern',
    organization: 'Airbnb, Inc.',
    logo: '🏠',
    category: 'Internships',
    description: 'Join the guest search team to craft responsive React components and node backend controllers using Next.js.',
    longDescription: 'Airbnb SWE interns are fully integrated into our standard feature loops. Help optimize performance on listings pages, configure server-side rendering routes, and upgrade design components under strict WCAG accessibility rules.',
    stipend: '$8,200/mo + Travel grants',
    location: 'San Francisco, CA / Remote-Friendly',
    deadlineDate: '2026-06-10',
    daysLeft: 6,
    skillsRequired: ['React.js', 'TypeScript', 'Node.js', 'Next.js', 'CSS', 'WCAG'],
    difficulty: 'Intermediate',
    matchScore: 91,
    isFeatured: false
  },
  {
    id: 'icpc-training-camp',
    title: 'ICPC Advanced Competitive Programming Camp',
    organization: 'CodeForces Alliance',
    logo: '🏅',
    category: 'Competitions',
    description: 'A rigorous competitive coding bootcamp led by legendary red-coders to master graph algorithms, trees, and dynamic programming.',
    longDescription: 'Train directly for your regional ICPC programming contests with daily virtual sets, editorial breakdowns, 1-on-1 performance diagnostics, and algorithmic acceleration maps. Top participants get direct referrals to Google, HFTs, and Openai engineering teams.',
    stipend: 'Direct Engineering Interview Pipelines',
    location: 'Virtual',
    deadlineDate: '2026-06-25',
    daysLeft: 21,
    skillsRequired: ['C++', 'Algorithms', 'Data Structures', 'Competitive Programming', 'Mathematics'],
    difficulty: 'Advanced',
    matchScore: 80,
    isFeatured: false
  }
];

export const initialApplicationCards: ApplicationTrackerCard[] = [
  {
    id: 'app-1',
    opportunityId: 'gsoc-2025',
    title: 'Google Summer of Code 2025',
    organization: 'Google Open Source',
    category: 'Open Source',
    stage: 'Under Review',
    appliedDate: '2026-06-01',
    notes: 'Submitted proposal draft to mentor. Got constructive feedback on API schemas and refactoring.',
    matchScore: 94
  },
  {
    id: 'app-2',
    opportunityId: 'mlh-hackathon-2025',
    title: 'MLH Global Catalyst Hackathon',
    organization: 'Major League Hacking',
    category: 'Hackathons',
    stage: 'Applied',
    appliedDate: '2026-06-03',
    notes: 'Team formed with 3 peers from college. Working on spatial widgets.',
    matchScore: 89
  },
  {
    id: 'app-3',
    opportunityId: 'meta-swe-intern',
    title: 'Meta Software Engineering Internship',
    organization: 'Meta Platforms Inc.',
    category: 'Internships',
    stage: 'Interview',
    appliedDate: '2026-05-24',
    notes: 'Round 1 tech screening scheduled on June 10. Focus on Graph traversals and Trie data structures.',
    matchScore: 92
  },
  {
    id: 'app-4',
    opportunityId: 'girlscript-soc',
    title: 'GirlScript Summer of Code 2025',
    organization: 'GirlScript Foundation',
    category: 'Open Source',
    stage: 'Selected',
    appliedDate: '2026-05-15',
    notes: 'Selected as top 5% candidate! Project contributions start soon. Super thrilled.',
    matchScore: 96
  },
  {
    id: 'app-5',
    title: 'Amazon SDE Intern Role',
    organization: 'Amazon',
    category: 'Internships',
    stage: 'Rejected',
    appliedDate: '2026-05-10',
    notes: 'Completed OA but unfortunately got full resume reject. Applying next year!',
    matchScore: 84
  }
];

export const initialUserProfile = {
  name: 'Arjun Sharma',
  email: 'arjun.sharma@iitd.edu',
  role: 'Computer Science Undergrad',
  bio: 'Passionate full-stack developer and open source contributor. Eager to solve complex scaling issues, design stunning user interfaces, and build automated developer tools.',
  avatar: '👨‍💻',
  skills: ['React.js', 'TypeScript', 'Node.js', 'Python', 'Git', 'Tailwind CSS', 'SQL'],
  interests: ['Frontend', 'AI/ML', 'Open Source', 'Hackathons'],
  goals: ['High Stipend', 'Industry Branding', 'Remote work'],
  resumeName: 'Arjun_Sharma_CS_Resume.pdf',
  membershipPlan: 'Free' as const
};

export const initialActivityLog: ActivityLog[] = [
  {
    id: 'act-1',
    text: 'Updated your skill set on profile (Added SQL and Tailwind CSS)',
    timestamp: '2 hours ago',
    type: 'profile'
  },
  {
    id: 'act-2',
    text: 'Bookmarked "Google Summer of Code 2025" for quick reference',
    timestamp: '5 hours ago',
    type: 'bookmark'
  },
  {
    id: 'act-3',
    text: 'Moved "Meta Software Engineering Internship" to the Interview Stage',
    timestamp: '1 day ago',
    type: 'application'
  },
  {
    id: 'act-4',
    text: 'Generated your first personalized AI Match Report',
    timestamp: '2 days ago',
    type: 'ai'
  }
];
